services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn ecommerce_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce_backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
    postDeploy:
      - python manage.py migrate
      - python manage.py loaddata categories.json
      - python manage.py loaddata products.json
