services:
  - type: web
    name: ecommerce-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
      python manage.py loaddata categories.json
      python manage.py loaddata products.json
    startCommand: gunicorn ecommerce.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings